# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.env: '%env(APP_ENV)%'
    locale: 'hu'
    locales: ['hu', 'en', 'de']
    file_upload_dir: '%env(FILE_UPLOAD_DIR)%'
    mailer_from_address: '%env(MAILER_FROM_ADDRESS)%'
    simple.env: '%env(SIMPLE_ENV)%'
    company_data: '%env(COMPANY_DATA)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Admin/Form/'


    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Admin\Controller\:
        resource: '../src/Admin/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    form.type.translatable:
        class: App\Admin\Form\TranslatableType
        arguments: [ '@doctrine.orm.default_entity_manager', '@validator', '@parameter_bag', '%locales%', '%locale%' ]
        tags:
            - { name: form.type, alias: translatable }
